name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/abhishek.jpg
  
  fonts:
  - family: PoiretOne
    fonts:
    - asset: fonts/PoiretOne-Regular.ttf
    
  - family: Roboto
    fonts:
    - asset: fonts/Roboto-Light.ttf